### ISSUE TITLE
Can not install on os x / python 3.5

### ISSUE THREAD

**Issue by ivecrs** [dizballanze/do-latency#2]
`p2mbot@mbp:~$ pip install do-latency
Collecting do-latency
  Downloading do-latency-0.2.1.tar.gz
Collecting pyping==0.0.4 (from do-latency)
  Downloading pyping-0.0.4.tar.gz
Collecting terminaltables==2.1.0 (from do-latency)
  Downloading terminaltables-2.1.0.tar.gz
Collecting tqdm==3.8.0 (from do-latency)
  Downloading tqdm-3.8.0-py2.py3-none-any.whl
Installing collected packages: pyping, terminaltables, tqdm, do-latency
  Running setup.py install for pyping ... done
  Running setup.py install for terminaltables ... done
  Running setup.py install for do-latency ... error
    Complete output from command /Users/p2mbot/.pyenv/versions/3.5.1/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/ss/g4j8j5kd4ms589b_jjbhfs9h0000gn/T/pip-build-7w5z4iu2/do-latency/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/ss/g4j8j5kd4ms589b_jjbhfs9h0000gn/T/pip-rdrczn3g-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/do_latency
    copying do_latency/__init__.py -> build/lib/do_latency
    copying do_latency/__main__.py -> build/lib/do_latency
    copying do_latency/do_latency.py -> build/lib/do_latency
    copying do_latency/download.py -> build/lib/do_latency
    copying do_latency/ping.py -> build/lib/do_latency
    running install_lib
    creating /Users/p2mbot/.pyenv/versions/3.5.1/lib/python3.5/site-packages/do_latency
    copying build/lib/do_latency/__init__.py -> /Users/p2mbot/.pyenv/versions/3.5.1/lib/python3.5/site-packages/do_latency
    copying build/lib/do_latency/__main__.py -> /Users/p2mbot/.pyenv/versions/3.5.1/lib/python3.5/site-packages/do_latency
    copying build/lib/do_latency/do_latency.py -> /Users/p2mbot/.pyenv/versions/3.5.1/lib/python3.5/site-packages/do_latency
    copying build/lib/do_latency/download.py -> /Users/p2mbot/.pyenv/versions/3.5.1/lib/python3.5/site-packages/do_latency
    copying build/lib/do_latency/ping.py -> /Users/p2mbot/.pyenv/versions/3.5.1/lib/python3.5/site-packages/do_latency
    byte-compiling /Users/p2mbot/.pyenv/versions/3.5.1/lib/python3.5/site-packages/do_latency/__init__.py to __init__.cpython-35.pyc
    byte-compiling /Users/p2mbot/.pyenv/versions/3.5.1/lib/python3.5/site-packages/do_latency/__main__.py to __main__.cpython-35.pyc
    byte-compiling /Users/p2mbot/.pyenv/versions/3.5.1/lib/python3.5/site-packages/do_latency/do_latency.py to do_latency.cpython-35.pyc
    byte-compiling /Users/p2mbot/.pyenv/versions/3.5.1/lib/python3.5/site-packages/do_latency/download.py to download.cpython-35.pyc
    byte-compiling /Users/p2mbot/.pyenv/versions/3.5.1/lib/python3.5/site-packages/do_latency/ping.py to ping.cpython-35.pyc
    running install_data
    error: can't copy 'LICENSE': doesn't exist or not a regular file

    ----------------------------------------
Command "/Users/p2mbot/.pyenv/versions/3.5.1/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/ss/g4j8j5kd4ms589b_jjbhfs9h0000gn/T/pip-build-7w5z4iu2/do-latency/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/ss/g4j8j5kd4ms589b_jjbhfs9h0000gn/T/pip-rdrczn3g-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/ss/g4j8j5kd4ms589b_jjbhfs9h0000gn/T/pip-build-7w5z4iu2/do-latency
p2mbot@mbp:~$`

**Comment by dizballanze** [comment]
It works only on Python 2.7 for now.

**Comment by berserkerX86** [comment]
Had the same problem, worked with 2.7, thanks

**Comment by dizballanze** [comment]
fixed !
